/*
 * Jessica DeWitt - Start working on the UI/UX.
 * Should be able to input a key, a letter to omit, a 5x5 grid and space for decoded phrase.
 */
package com.playfair.ui;

import com.playfair.backend.CipherGrid;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.stage.Stage;
import java.util.List;

/**
 * Playfair Cipher UI
 *
 * This class creates the UI for the Playfair Cipher application.
 * It provides input fields for the cipher key and missing letter selection,
 * displays the 5x5 cipher grid generated by the backend CipherGrid class,
 * and includes placeholder buttons for future encryption/decryption functionality.
 * - 5x5 grid display
 * - Text input for cipher key
 * - Dropdown menu for missing letter selection
 */
public class PlayfairUI extends Application {

    // UI COMPONENTS

    /** Text field where user enters the cipher key (example: "APPLE", "PLAYFAIR") */
    private TextField keyField;

    /** Dropdown menu for selecting which letter to omit from the 5x5 grid
     *  Since we need 25 letters for a 5x5 grid, one letter must be omitted from the 26-letter alphabet.
     *  Common omissions: J, X, Q, etc.
     */
    private ComboBox<String> missingLetterCombo;

    /** Text area where user types the message they want to encrypt or decrypt */
    private TextArea inputArea;

    /** Text area where results (encrypted/decrypted text) will be displayed */
    private TextArea outputArea;

    /** 2D array of Labels that visually represent the 5x5 cipher grid
     *  gridLabels[row][col] corresponds to the letter at that position in the cipher matrix
     */
    private Label[][] gridLabels = new Label[5][5];

    /**
     * Main entry point for the JavaFX application.
     * Sets up the window layout and initializes all UI components.
     *
     * @param primaryStage The main window of the application
     */
    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Playfair Cipher");

        // Main layout container with five regions: top, bottom, left, right, center
        BorderPane mainLayout = new BorderPane();
        mainLayout.setPadding(new Insets(20));
        mainLayout.setStyle("-fx-background-color: #f0f0f0;");

        // all sections of the UI
        mainLayout.setTop(createTitleSection());        // Title at the top
        mainLayout.setCenter(createGridSection());      // 5x5 grid in the center
        mainLayout.setLeft(createInputSection());       // Input controls on the left
        mainLayout.setRight(createOutputSection());     // Results panel on the right
        mainLayout.setBottom(createButtonSection());    // Action buttons at the bottom

        // Creating and displaying the scene
        Scene scene = new Scene(mainLayout, 1000, 650);
        primaryStage.setScene(scene);
        primaryStage.show();

        //default grid with key="APPLE" and missing letter="J"
        generateGrid();
    }

    /**
     * Creates the title section displayed at the top of the window.
     *
     * @return HBox containing the title label
     */
    private HBox createTitleSection() {
        HBox hbox = new HBox();
        hbox.setAlignment(Pos.CENTER);
        hbox.setPadding(new Insets(0, 0, 20, 0));

        Label title = new Label("Playfair Cipher");
        title.setFont(Font.font("Arial", FontWeight.BOLD, 28));

        hbox.getChildren().add(title);
        return hbox;
    }

    /**
     * Creates the left panel containing all input controls.
     * Includes:
     * - Key input field (for cipher key)
     * - Missing letter dropdown (selecting which letter to omit)
     * - Message input area (text to encrypt/decrypt)
     * - Generate Grid button (updates the grid based on current inputs)
     *
     * @return VBox containing all input components
     */
    private VBox createInputSection() {
        VBox vbox = new VBox(15);
        vbox.setPadding(new Insets(10));
        vbox.setPrefWidth(250);
        vbox.setStyle("-fx-background-color: white; -fx-border-color: #ccc; -fx-border-radius: 5; -fx-padding: 15;");

        // ===== KEY INPUT SECTION =====
        Label keyLabel = new Label("Cipher Key:");
        keyLabel.setFont(Font.font("Arial", FontWeight.BOLD, 14));

        keyField = new TextField();
        keyField.setPromptText("Enter key (e.g., APPLE, PLAYFAIR)");
        keyField.setText("APPLE");  // Default key

        // ===== MISSING LETTER DROPDOWN =====
        Label missingLabel = new Label("Missing Letter:");
        missingLabel.setFont(Font.font("Arial", FontWeight.BOLD, 14));

        // Dropdown menu for missing letter selection
        // Common omissions in Playfair cipher: J, X, Q, etc.
        missingLetterCombo = new ComboBox<>();
        missingLetterCombo.getItems().addAll("J", "X", "Q", "Y", "Z");  // Common missing letters
        missingLetterCombo.setValue("J");  // Default selection
        missingLetterCombo.setPrefWidth(80);
        missingLetterCombo.setEditable(false);  // User can only select from dropdown, not type custom

        // ===== MESSAGE INPUT SECTION =====
        Label messageLabel = new Label("Message:");
        messageLabel.setFont(Font.font("Arial", FontWeight.BOLD, 14));

        inputArea = new TextArea();
        inputArea.setPromptText("Enter message to encrypt/decrypt");
        inputArea.setPrefRowCount(5);
        inputArea.setWrapText(true);  // Text will wrap to next line

        // ===== GENERATE GRID BUTTON =====
        Button generateBtn = new Button("Generate Grid");
        generateBtn.setMaxWidth(Double.MAX_VALUE);
        generateBtn.setStyle("-fx-background-color: #4CAF50; -fx-text-fill: white; -fx-font-weight: bold;");
        generateBtn.setOnAction(e -> generateGrid());  // Calls generateGrid when clicked

        // all components to the vertical box
        vbox.getChildren().addAll(
                keyLabel, keyField,
                missingLabel, missingLetterCombo,
                messageLabel, inputArea,
                generateBtn
        );

        return vbox;
    }

    /**
     * Creates the center panel containing the 5x5 cipher grid.
     * The grid is represented by a 5x5 array of Labels that will display
     * the letters from the cipher matrix generated by CipherGrid.
     *
     * @return VBox containing the grid title and the grid itself
     */
    private VBox createGridSection() {
        VBox vbox = new VBox(15);
        vbox.setAlignment(Pos.CENTER);

        Label gridTitle = new Label("5x5 Cipher Grid");
        gridTitle.setFont(Font.font("Arial", FontWeight.BOLD, 16));

        // GridPane: grid layout for the 5x5 cells
        GridPane gridPane = new GridPane();
        gridPane.setHgap(5);  // Horizontal gap between cells
        gridPane.setVgap(5);  // Vertical gap between cells
        gridPane.setAlignment(Pos.CENTER);

        // 5x5 grid of labels (25 cells total)
        for (int row = 0; row < 5; row++) {
            for (int col = 0; col < 5; col++) {
                Label label = new Label("?");  // Placeholder until grid is generated
                label.setFont(Font.font("Arial", FontWeight.BOLD, 24));
                label.setMinSize(70, 70);  // Fixed size for each cell
                label.setStyle(
                        "-fx-border-color: black;" +
                                "-fx-border-width: 2;" +
                                "-fx-background-color: white;" +
                                "-fx-alignment: center;"
                );

                // Store reference to label for later update
                gridLabels[row][col] = label;
                // Added to GridPane at column=col, row=row
                gridPane.add(label, col, row);
            }
        }

        vbox.getChildren().addAll(gridTitle, gridPane);
        return vbox;
    }

    /**
     * Creates the right panel where encryption/decryption results are displayed.
     * This panel is a placeholder and will be done
     * when encryption/decryption is added in next sprints.
     *
     * @return VBox containing output areas
     */
    private VBox createOutputSection() {
        VBox vbox = new VBox(15);
        vbox.setPadding(new Insets(10));
        vbox.setPrefWidth(300);
        vbox.setStyle("-fx-background-color: white; -fx-border-color: #ccc; -fx-border-radius: 5; -fx-padding: 15;");

        Label outputTitle = new Label("Results");
        outputTitle.setFont(Font.font("Arial", FontWeight.BOLD, 16));

        Label resultLabel = new Label("Processed Message:");
        resultLabel.setFont(Font.font("Arial", FontWeight.BOLD, 14));

        // Output area: displays encrypted/decrypted text (read-only)
        outputArea = new TextArea();
        outputArea.setEditable(false);  // Users cannot type here
        outputArea.setPrefRowCount(10);
        outputArea.setWrapText(true);
        outputArea.setPromptText("Result will appear here...");

        vbox.getChildren().addAll(outputTitle, resultLabel, outputArea);

        return vbox;
    }

    /**
     * Creates the bottom panel with action buttons.
     * Buttons:
     * - ENCRYPT: Will encrypt the input message (to be implemented)
     * - DECRYPT: Will decrypt the input message (to be implemented)
     * - CLEAR: Resets all fields to default values
     *
     * @return HBox containing all buttons
     */
    private HBox createButtonSection() {
        HBox hbox = new HBox(15);
        hbox.setAlignment(Pos.CENTER);
        hbox.setPadding(new Insets(20, 0, 0, 0));

        // ENCRYPT BUTTON
        Button encryptBtn = new Button("ENCRYPT");
        encryptBtn.setPrefWidth(100);
        encryptBtn.setStyle("-fx-background-color: #2196F3; -fx-text-fill: white; -fx-font-weight: bold;");
        encryptBtn.setOnAction(e -> encryptMessage());  // Placeholder functionality

        // DECRYPT BUTTON
        Button decryptBtn = new Button("DECRYPT");
        decryptBtn.setPrefWidth(100);
        decryptBtn.setStyle("-fx-background-color: #FF9800; -fx-text-fill: white; -fx-font-weight: bold;");
        decryptBtn.setOnAction(e -> decryptMessage());  // Placeholder functionality

        // CLEAR BUTTON
        Button clearBtn = new Button("CLEAR");
        clearBtn.setPrefWidth(100);
        clearBtn.setStyle("-fx-background-color: #f44336; -fx-text-fill: white; -fx-font-weight: bold;");
        clearBtn.setOnAction(e -> clearAll());  // Resets everything

        hbox.getChildren().addAll(encryptBtn, decryptBtn, clearBtn);

        return hbox;
    }

    /**
     * Generates the 5x5 cipher grid based on the current key and missing letter.
     *
     * Process:
     * 1. Retrieve key from text field and missing letter from dropdown
     * 2. Validate inputs (key not empty, missing letter selected)
     * 3. Call CipherGrid methods to generate the cipher matrix:
     *    - CleanKey() - removes duplicate letters from key
     *    - RearrangeAlphabet() - creates 25-letter alphabet with key first
     *    - PopulateGrid() - fills the 5x5 grid
     * 4. Retrieve the grid using getGrid() and update the UI labels
     *
     * This method demonstrates integration between UI and backend CipherGrid class.
     */
    private void generateGrid() {
        // Get input values
        String key = keyField.getText().trim().toUpperCase();
        String missingLetter = missingLetterCombo.getValue();  // Get selected value from dropdown

        // Validate key input
        if (key.isEmpty()) {
            showAlert("Error", "Please enter a key");
            return;
        }

        // Validate missing letter selection (should never be null since dropdown has default)
        if (missingLetter == null || missingLetter.isEmpty()) {
            showAlert("Error", "Please select a missing letter");
            return;
        }

        try {
            // BACKEND INTEGRATION
            // These methods are from the CipherGrid class

            // 1.Clean the key (remove duplicate letters)
            List<Character> cleanKey = CipherGrid.CleanKey(key);

            // 2.Rearrange alphabet with key at front and missing letter removed
            String rearrangedAlpha = CipherGrid.RearrangeAlphabet(cleanKey, missingLetter);

            // 3.Populate the 5x5 grid with the rearranged alphabet
            CipherGrid.PopulateGrid(rearrangedAlpha);

            // 4.Get the generated grid for display
            String[][] grid = CipherGrid.getGrid();

            //  UPDATE UI
            // Loop through all 25 cells and update the label text
            for (int row = 0; row < 5; row++) {
                for (int col = 0; col < 5; col++) {
                    if (grid[row][col] != null) {
                        gridLabels[row][col].setText(grid[row][col]);
                    }
                }
            }

            // Display success message in output area
            outputArea.setText("Grid generated successfully\nKey: " + key + "\nMissing letter: " + missingLetter);

        } catch (Exception e) {
            showAlert("Error", "Error generating grid: " + e.getMessage());
        }
    }

    /**
     * Placeholder for encryption functionality.
     * Currently only displays the message that would be encrypted.
     * Full implementation will be added in a future sprint when
     * encryption logic is integrated with CipherGrid.
     */
    private void encryptMessage() {
        String message = inputArea.getText().trim().toUpperCase();
        if (message.isEmpty()) {
            showAlert("Error", "Please enter a message to encrypt");
            return;
        }

        // Remove any non-letter characters (numbers, punctuation, etc.)
        message = message.replaceAll("[^A-Z]", "");

        // TODO: Implement actual encryption using CipherGrid
        // This will be implemented in a future sprint
        outputArea.setText("Encrypting: " + message + "\n\nNote: Encryption functionality will be implemented in the next sprint.");
    }

    /**
     * Placeholder for decryption functionality.
     * Currently only displays the message that would be decrypted.
     * Full implementation will be added in a future sprint when
     * decryption logic is integrated with CipherGrid.
     */
    private void decryptMessage() {
        String message = inputArea.getText().trim().toUpperCase();
        if (message.isEmpty()) {
            showAlert("Error", "Please enter a message to decrypt");
            return;
        }

        // Remove any non-letter characters (numbers, punctuation, etc.)
        message = message.replaceAll("[^A-Z]", "");

        // TODO: Implement actual decryption using CipherGrid
        // This will be implemented in a future sprint
        outputArea.setText("Decrypting: " + message + "\n\nNote: Decryption functionality will be implemented in the next sprint.");
    }

    /**
     * Resets all input fields to their default values and regenerates the grid.
     * Default values:
     * - Key: "APPLE"
     * - Missing letter: "J" (selected in dropdown)
     * - Message input: cleared
     * - Output area: cleared
     */
    private void clearAll() {
        keyField.setText("APPLE");
        missingLetterCombo.setValue("J");  // Reset dropdown to default
        inputArea.clear();
        outputArea.clear();
        generateGrid();  // Regenerate grid with default values
    }

    /**
     * Displays an error alert dialog with the specified title and message.
     * Used for validation errors and exception handling.
     *
     * @param title The title of the alert window
     * @param message The error message to display
     */
    private void showAlert(String title, String message) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    /**
     * Main method to launch the JavaFX application.
     *
     * @param args Command line arguments (not used)
     */
    public static void main(String[] args) {
        launch(args);
    }
}
